services:
  - type: web
    name: amarjit-electrical-store
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: amarjit-store-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false

databases:
  - name: amarjit-store-db
    databaseName: amarjit_electrical_store
    user: amarjit_user
    plan: free